options:
  retrofit-series:
    type: string
    default:
    description: |
      Ubuntu series (eg. 'bionic') to look for in Glance to use as base
      for the retrofitting process.
      .
      Default is to use most recent LTS.
  retrofit-uca-pocket:
    type: string
    default:
    description: |
      Name of Ubuntu Cloud Archive pocket to add to the image being
      retrofitted.
      .
      Default is 'ussuri' if ``retrofit-series`` is 'bionic', for other
      releases no UCA pocket will be added unless specified.
  amp-image-tag:
    type: string
    default: ''
    description: |
      When set the charm will add tag to any newly created images.
      .
      Note that the charm will allways add the ``octavia-diskimage-retrofit``
      tag to created images, this is for convenience and may be used by the
      charm for housekeeping in the future.
